### ISSUE TITLE
Build from fork not working

### ISSUE THREAD

**Issue by peterennis** [ionic-team/ionic-pwa-toolkit#1]
**Stencil version:** (run `npm list @stencil/core` from a terminal/cmd prompt and paste output below):

Running Windows 10 x64
Git Bash client

```
$ npm list @stencil/core
@stencil/starter@0.0.1 C:\ae\aedhpwa
`-- @stencil/core@0.1.1-0
```

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
Build hangs

**Expected behavior:**
I do not know

**Steps to reproduce:**
Fork the repo
Follow build instructions using forked repo

![capture232](https://user-images.githubusercontent.com/140737/34510565-c296be00-f009-11e7-8c66-14f4f1e23c5f.png)

The system is stuck here:

![capture231](https://user-images.githubusercontent.com/140737/34510576-dcf3214e-f009-11e7-9d1b-e89bdedc2424.png)

**Comment by jgw96** [comment]
Hey! This is actually a known issue with Stencil https://github.com/ionic-team/stencil/issues/414. Thanks for opening an issue with us!
