### ISSUE TITLE
Missing types for Ionic components

### ISSUE THREAD

**Issue by Cammisuli** [ionic-team/ionic-pwa-toolkit#101]
With the latest release (`@ionic/core@one` and `@stencil/core@one`) typings seem to be broken for Ionic components. 

Hovering over the JSX reveals no information. 
![image](https://user-images.githubusercontent.com/4332460/57961302-fed42e00-78db-11e9-9d29-565892804b97.png)

I managed to get around and fix this by extending the JSX interface in `interfaces.d.ts` like so:
```typescript
import { JSX as JsxIonic } from '@ionic/core';

declare module '@stencil/core' {
  export namespace JSX {
    interface IntrinsicElements extends JsxIonic.IntrinsicElements {}
  }
}

```

With the above applied, type information appears for Ionic components:
![image](https://user-images.githubusercontent.com/4332460/57961331-3511ad80-78dc-11e9-8d59-8a5130cf7846.png)

If this an acceptable solution to this, I'll be more than happy to create a PR and update the repo. If there's already something in progress that fixes this issue, then I'll be happy with that too. 

Thanks!

**Comment by arjunyel** [comment]
Ionic and Stencil have been updated, should be fixed now, thank you for the report!
