### ISSUE TITLE
Routing is slow at first when hosted on the web (Firebase)

### ISSUE THREAD

**Issue by Bandito11** [ionic-team/ionic-pwa-toolkit#109]
I also made the issue here because I am unsure if it is a ionic issue or a toolkit issue.

See the web app as an example: https://millefollium.web.app

Issue: When going from page to page and opening a modal the app is really slow (at start) to go traverse from page to page. After that first "run" it runs normally. That doesn't happen when running locally. If I close the tab it runs normally but when I clear the cache it happens again.

This happens on Firefox and Chrome.

https://github.com/Bandito11/millefollium

https://github.com/Bandito11/millefollium/blob/master/package.json
    "@stencil/core": "1.4.0",
    "@ionic/core": "4.9.1",

**Comment by arjunyel** [comment]
Check out the network tab while you navigate around, you'll see components are being lazy loaded when requested so a user will only experience that once. Awesome looking app!
