### ISSUE TITLE
Issues when running on Windows

### ISSUE THREAD

**Issue by dalenguyen** [ionic-team/ionic-pwa-toolkit#15]
I clone a fresh ionic-pwa-toolkit, then run 

```
npm install 
```
However, the npm start command, it shows errors 

![image](https://user-images.githubusercontent.com/14116156/35992416-371f0db4-0cd8-11e8-81e1-de6cd1a371ad.png)

OS: Windows 10
NPM: 5.6.0
Node: 8.9.2

**Comment by jgw96** [comment]
Hello! Thanks for using the Ionic PWA Toolkit! I just updated the repo to use the latest version of Stencil and Ionic which fixes this old issue. To update you can do a fresh clone of this repo or do a git pull.
