### ISSUE TITLE
Build pwa to reference specific subfolder

### ISSUE THREAD

**Issue by askilondz** [ionic-team/ionic-pwa-toolkit#21]
I'm experimenting adding the sources of the `www` output folder to a public subfolder in my laravel application, `public/pwa`. The pwa loads fine when going to `myproject.com/pwa` but the service worker and other relative links fail because they are all pointing to `/` when really i need them to point to `/pwa/` since the pwa is not at the root of my site. 

Is there a way to set this root in the PWA toolkit application source so when running `npm run build` all file paths generated point to the specified root? I thought this would work by modifyng the `host.config.json` but no avail.

**Comment by jgw96** [comment]
Hello! Thanks for using the Ionic PWA Toolkit. Since this is more of a support type question I recommend joining our Stencil Slack (https://stencil-worldwide.herokuapp.com/) and asking on there. Again, thanks for using the Ionic PWA Toolkit!
