### ISSUE TITLE
Unfound component tags: Component tag "my-app" is defined in a bundle but no matching component was found within this app

### ISSUE THREAD

**Issue by kael** [ionic-team/ionic-pwa-toolkit#22]
**Resources:**
Before submitting an issue, please consult our [docs](https://stenciljs.com/).

**Stencil version:** (run `npm list @stencil/core` from a terminal/cmd prompt and paste output below):

```
@stencil/starter@0.0.1 /home/kael/dev/test/my-pwa
└── @stencil/core@0.5.1 
```

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

Fetching the last master commits, something's broken out of the box:

```bash
[ ERROR ]  Component tag "my-app" is defined in a bundle but no matching component was found within this app or its
           collections. at b.components.map.tag
           (/home/kael/dev/test/my-pwa/node_modules/@stencil/core/dist/compiler/index.js:8235:23) at Array.map
           (<anonymous>) at configBundles.map.b
           (/home/kael/dev/test/my-pwa/node_modules/@stencil/core/dist/compiler/index.js:8231:14) at Array.map
           (<anonymous>) at getUserConfigEntryTags
           (/home/kael/dev/test/my-pwa/node_modules/@stencil/core/dist/compiler/index.js:8229:10) at
           generateEntryModules
           (/home/kael/dev/test/my-pwa/node_modules/@stencil/core/dist/compiler/index.js:8060:44) at
           /home/kael/dev/test/my-pwa/node_modules/@stencil/core/dist/compiler/index.js:14960:34 at
           Generator.next (<anonymous>) at fulfilled
           (/home/kael/dev/test/my-pwa/node_modules/@stencil/core/dist/compiler/index.js:14924:58) at
           <anonymous>
```

Adding the removed bundle components in [stencil.config.js](https://github.com/ionic-team/ionic-pwa-toolkit/commit/3ac00264bd944cbb4aac0290869cff891aa426b4#diff-b32c669893837bd30e10c29cd17fcf9cL1), doesn't fix the thing.

BTW, not sure that running `git remote rm origin` is the best way to keep up-to-date with the project, I've renamed this remote and I'm rebasing on my local directory. Unless there's a better way ?

**Comment by jgw96** [comment]
Hello! Thanks for using the PWA Toolkit! I just updated this repo to the latest of everything which fixes this issue. If you do a fresh `git pull` or `git clone` and then run `npm install` you should be good to go.

**Comment by kael** [comment]
Thank you for the fix.

Now I'm coming across another issue https://github.com/ionic-team/stencil/issues/560

Seems that having a stable release with a working config of Stencil on Linux is a bit complicated. It'd be awesome if you could use version number in _package.json_ instead of `latest`, and tag also milestones. It's difficult to track working configurations, though.
