### ISSUE TITLE
Cannot read icon file

### ISSUE THREAD

**Issue by peterennis** [ionic-team/ionic-pwa-toolkit#27]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
https://raw.githubusercontent.com/ionic-team/ionic-pwa-toolkit/master/src/assets/icon/favicon.ico

Download and try to open with Icon Editor

![capture242](https://user-images.githubusercontent.com/140737/36770240-1527a2c2-1bfe-11e8-9afa-ad7bccb65199.png)

**Expected behavior:**
It should be an icon
Windows 10, x64

What is the actual format? How do I create it when the file is not recognized in
a Windows icon editor?
Tested from clone and also direct download.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [slack channel](https://stencil-worldwide.herokuapp.com/). Thanks for using Stencil!
