### ISSUE TITLE
button attribute menuToggle prevents compilation

### ISSUE THREAD

**Issue by cdock1029** [ionic-team/ionic-pwa-toolkit#33]
**Resources:**
Before submitting an issue, please consult our [docs](https://stenciljs.com/).

**Stencil version:** (run `npm list @stencil/core` from a terminal/cmd prompt and paste output below):

```
@stencil/core@0.6.1
```

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
adding `menuToggle` attribute to a button produces typescript compilation error:

`Property 'menuToggle' does not exist on type 'IonButtonAttributes'.`

**Expected behavior:**
Using ionic components as documented just works.

**Steps to reproduce:**
Try to implement button component as described here:
https://ionicframework.com/docs/api/components/toolbar/Navbar/

**Related code:**

```jsx
<button ion-button icon-only menuToggle>
  <ion-icon name='menu'></ion-icon>
</button>
```

**Other information:**
I'm new to Ionic. Is there documentation about using it with Stencil ?

**Comment by arjunyel** [comment]
Try `npm i --save @ionic/core @stencil/core`

**Comment by cdock1029** [comment]
I kinda figured out that a lot of the library is in flux switching to stencil. 

The main point here is that the docs I was referencing aren't applicable to the updated widgets.
