### ISSUE TITLE
Browser back button must be invoked twice before going back

### ISSUE THREAD

**Issue by insightcoder** [ionic-team/ionic-pwa-toolkit#39]
**Stencil version:** (run `npm list @stencil/core` from a terminal/cmd prompt and paste output below):
```
`-- @stencil/core@0.7.7
```

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
When using the sample app, when I click on the profile page, the url appropriately changes to /profile/stencil.  If I click on the ion-back-button, we are routed correctly back to /.  However, if I click on the browser back button, nothing happens.  If I click on the browser back button a second time, we are routed back to /.  

**Expected behavior:**
I expect a single browser back click to navigate back to root, rather than requiring two clicks. 

**Steps to reproduce:**
I think it is described enough in Current behavior.  Let me know otherwise!

**Comment by jgw96** [comment]
Hey! I just updated the toolkit to use the latest release of @ionic/core which has a fix for this issue. Thanks for opening an issue with us!

**Comment by insightcoder** [comment]
@jgw96 Excellent.  Thanks!   When developing with this toolkit, is it fine to just update the underlying npm dependencies to the latest, or are those carefully coordinated?
