### ISSUE TITLE
Cannot read property 'pushManager' of undefined

### ISSUE THREAD

**Issue by amreladawy** [ionic-team/ionic-pwa-toolkit#4]
**Stencil version:** (run `npm list @stencil/core` from a terminal/cmd prompt and paste output below):

```
@stencil/core@0.1.3
```

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

Just start with cloning the project and start it but got the following error while turning on notifications.
```
Uncaught (in promise) TypeError: Cannot read property 'pushManager' of undefined
    at navigator.serviceWorker.getRegistration.then (app-profile.js:41)
    at <anonymous>
navigator.serviceWorker.getRegistration.then @ app-profile.js:41
Promise resolved (async)
handleSub @ app-profile.js:39
subscribeToNotify @ app-profile.js:34
ev @ app.core.js:702
domApi.$dispatchEvent @ app.core.js:582
Context.emit @ app.core.js:1873
emit @ app.core.js:669
checkedChanged @ ion-toggle.md.js:91
setValue @ app.core.js:1185
setComponentProp @ app.core.js:1102
onDragEnd @ ion-toggle.md.js:127
pointerUp @ ion-gesture.js:622
onMouseUp @ ion-gesture.js:605
plt.domApi.$addEventListener.ev @ app.core.js:722
```
**Expected behavior:**

**Steps to reproduce:**

Just clone and start.
**Related code:**

```
            reg.pushManager.getSubscription().then((sub) => {
```

**Other information:**

Chrome Version 63.0.3239.132 (Official Build) (64-bit)

**Comment by Cammisuli** [comment]
Looks like it works when you do `npm run build` and run that compiled version.

**Comment by amreladawy** [comment]
I tried that, but still same error. What may be wrong with my setup?

**Comment by Cammisuli** [comment]
Yea, it looks like if we're in dev mode, service workers aren't registered. As seen here:
https://github.com/ionic-team/stencil/blob/master/src/compiler/html/generate-index-html.ts#L37-L40

**Comment by jgw96** [comment]
Hey all! This will be fixed in the next release of Stencil. When that release hits you will be able to run `npm run devWithSw` which will have the service worker enabled in dev. Thanks for using the Ionic PWA Toolkit!

**Comment by paritosh149** [comment]
Closing this issue with a commit by same name and "fix:" as prefix will link the commit and issue. Isn't it?
