### ISSUE TITLE
Remove the helpers code

### ISSUE THREAD

**Issue by mlynch** [ionic-team/ionic-pwa-toolkit#40]
There's a `helpers/util.ts` file with what appears to be an unused function `urlB64ToUint8Array`. Either way, we shouldn't have that kind of thing in here

**Comment by jgw96** [comment]
@mlynch Just to explain why this function is here, we are currently using this function here https://github.com/ionic-team/ionic-pwa-toolkit/blob/master/src/components/app-profile/app-profile.tsx#L21 to convert the key to the format that web push notifications needs. I got this function from the google web fundamentals docs on web push notifcations https://developers.google.com/web/fundamentals/push-notifications/subscribing-a-user. Is there a better way to do this that you're aware of?

**Comment by mlynch** [comment]
The issue is having the helpers file in general for a template app. The patterns we use are going to dictate to the community how they should lay out their app, and we should avoid having global helpers unless we are absolutely certain all apps will need it. If a certain component needs that, just include it in the component instead of making a global helper.
