### ISSUE TITLE
Modal not working on iPhone 6

### ISSUE THREAD

**Issue by cnhnet** [ionic-team/ionic-pwa-toolkit#42]
**Resources:**
Before submitting an issue, please consult our [docs](https://stenciljs.com/).

**Stencil version:** (run `npm list @stencil/core` from a terminal/cmd prompt and paste output below):

`-- @stencil/core@0.7.7

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

When using a modal in the PWA toolkit (import { ModalController } from '@ionic/core') the modal works and properly displays as designed on desktop web browsers and on my iPad, but it does not show up when on my iPhone 6 (when the modal is called in my iPhone, it does not show up but something does invisibly block the underlying page - cannot press buttons or navigate, etc.).
**Expected behavior:**
I expect the modal to show up in all devices including on iPhone devices.

**Steps to reproduce:**

Create a modal in the PWA toolkit and test it on a desktop and tablet device and then test to reproduce the issue on an iPhone (or maybe the same thing will occur on smaller devices - I don't know).

import { Component, Prop, State } from '@stencil/core';
import { ModalController } from '@ionic/core';

@Component({
    tag: 'app-logon',
    styleUrl: 'app-logon.scss'
})

export class AppLogOn {

    @Prop({ connect: 'ion-modal-controller' }) modalCtrl: ModalController;
    @State() modal: any;

    openHelp() {
        this.modalCtrl.create({
            component: 'app-help'
        }).then((modal) => {
            this.modal = modal;
            this.modal.present();
        }).catch((error) => {
            console.error(error.message);
        }
        )
    };

**Other information:**

**Comment by jgw96** [comment]
@cnhnet Could you try the latest version of the PWA Toolkit and see if you still have this issue? Thanks!

**Comment by cnhnet** [comment]
This is resolved in the latest version of the toolkit, thanks, Justin.
