### ISSUE TITLE
Evaluate app-profile.tsx

### ISSUE THREAD

**Issue by mlynch** [ionic-team/ionic-pwa-toolkit#49]
There's an awful lot of custom code in `app-profile.tsx` related to managing push notifications. I'm not convinced this is the way we want to tell users to interact with the push service.

This might be a good candidate for an external library or a reusable class we can provide instead of keeping the code in a single component. Unlike the helpers thing, push notifications is a common enough, easily abstracted concept, that it probably makes sense to provide a helper class or utility library for it.

Thoughts?

**Comment by jgw96** [comment]
I think this is a great idea! Could probably make this into a `@stencil/web-push` lib?
