### ISSUE TITLE
Uncaught (in promise) SyntaxError: Unexpected token export     at Object.<anonymous> (workbox-core.prod.js:1)     at Generator.next (<anonymous>)     at n (workbox-core.prod.js:1)     at workbox-core.prod.js:1

### ISSUE THREAD

**Issue by peterennis** [ionic-team/ionic-pwa-toolkit#54]
**Stencil version:** (run `npm list @stencil/core` from a terminal/cmd prompt and paste output below):

```
C:\ae\adaept.com\aepwa>npm list @stencil/core
@stencil/starter@0.0.1 C:\ae\adaept.com\aepwa
`-- @stencil/core@0.7.24
```

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

![capture275](https://user-images.githubusercontent.com/140737/38784636-97efac46-40c9-11e8-83b4-ae2842176b8a.png)

**Expected behavior:**
No errors

**Steps to reproduce:**
Latest version

**Related code:**

**Other information:**
https://aepwa-dev.firebaseapp.com/

**Comment by jgw96** [comment]
Hey! This is actually a chrome issue https://bugs.chromium.org/p/chromium/issues/detail?id=810469 . I responded to this issue to get it prioritized with the Chrome team and will be opening a new one if this one does not get any responses.

**Comment by peterennis** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=810469

This is marked as "WONTFIX" ???

It links to here:

https://github.com/GoogleChrome/workbox/issues/1433#issuecomment-381656479

Then this points to a new issue opened by @jeffposnik

https://bugs.chromium.org/p/chromium/issues/detail?id=833501

@jgw96 - I do not see anything from you. . .

**Comment by jholt1** [comment]
@peterennis https://bugs.chromium.org/p/chromium/issues/detail?id=810469#c4 is @jgw96 comment

**Comment by devliber** [comment]
@jgw96 @peterennis They have been merged into issue 832202, so the new URL is
https://bugs.chromium.org/p/chromium/issues/detail?id=832202

Indeed, it's a Chrome issue, can be reproduced using standard Cache API instead of Workbox (https://github.com/hwalab-developer/swesmit).
