### ISSUE TITLE
app icon not displaying correctly in Chrome

### ISSUE THREAD

**Issue by peterennis** [ionic-team/ionic-pwa-toolkit#55]
**Stencil version:** (run `npm list @stencil/core` from a terminal/cmd prompt and paste output below):

```
C:\ae\adaept.com\aepwa>npm list @stencil/core
@stencil/starter@0.0.1 C:\ae\adaept.com\aepwa
`-- @stencil/core@0.7.24
```

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
App icon does not show in Chrome

**Expected behavior:**
App icon displays in Chrome.
NOTE: It works in other browsers.

**Steps to reproduce:**
Chrome
![capture279-chrome](https://user-images.githubusercontent.com/140737/38789108-e40ae2e4-40ec-11e8-8927-8348f0b15a16.png)

Chrome Secure
![capture279-chrome-incognito](https://user-images.githubusercontent.com/140737/38789113-eb8008d8-40ec-11e8-93ed-44c9db39a234.png)

IE11
![capture276-ie11](https://user-images.githubusercontent.com/140737/38789116-f0d3b532-40ec-11e8-9907-e340bf70690f.png)

Edge
![capture277-edge](https://user-images.githubusercontent.com/140737/38789126-f7cb6402-40ec-11e8-8d22-ca23b5323f07.png)

Firefox
![capture278-firefox](https://user-images.githubusercontent.com/140737/38789127-fd2cedf8-40ec-11e8-9216-76a4aa617f32.png)

**Related code:**

**Other information:**
https://aepwa-dev.firebaseapp.com/

**Comment by peterennis** [comment]
https://github.com/peterennis/aepwa/commits/master

**Comment by jgw96** [comment]
@peterennis does the default Icon work? It works for me.

**Comment by peterennis** [comment]
Possible related #37 

The default Ionic icons worked, but that's not the point from my perspective :)
- or for anyone else wanting to customize.

A clear spec of what they should be (size/format/type/. . .) would help.

**Comment by jgw96** [comment]
Hey! So I think making sure a custom favicon is correct is a little out of scope of the toolkit, but after researching it looks like 16x16 is what your custom favicon should be. I am going to close this issue for now, thanks for using Stencil!

**Comment by peterennis** [comment]
I tried it on a different machine and it works.
Could be some caching related issue on Windows.

NOTE: Favicon has different sizes embedded, not just 16x16.

![capture1374](https://user-images.githubusercontent.com/140737/38887310-540bae16-422d-11e8-8877-eafa68346b5a.PNG)
