### ISSUE TITLE
Disappearing sw.js file and service worker in browser

### ISSUE THREAD

**Issue by cnhnet** [ionic-team/ionic-pwa-toolkit#57]
**Resources:**
Before submitting an issue, please consult our [docs](https://stenciljs.com/).

**Stencil version:** (run `npm list @stencil/core` from a terminal/cmd prompt and paste output below):

```
@stencil/core v0.7.24
```

**I'm submitting a ...**  (check one with "x")
[ X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
I'm not sure if I am misunderstanding something in the newest PWA toolkit, but sometimes when I run "npm run devWithSW" it deletes the sw.js file from the build and there is no service worker loaded in the browser. To get the sw.js back, I have to re-build ("npm run build"). But, after I rebuild and run "npm run devWithSW", it deletes the sw.js again.

Here is the sw.js in the www folder after build:
![0 after build](https://user-images.githubusercontent.com/37949129/38997048-5af62290-43a1-11e8-94a9-ff8637ea1359.jpg)

Note the sw.js is gone from the www folder after "npm run devWithSW":
![1 after devwithsw](https://user-images.githubusercontent.com/37949129/38997049-5b113bde-43a1-11e8-976e-ee94dfea4ce9.jpg)

Note that there is no service worker in the browser after "npm run devWithSW":
![2 after devwithsw](https://user-images.githubusercontent.com/37949129/38997051-5b2fadbc-43a1-11e8-84e2-b63e0331920f.jpg)

**Expected behavior:**
I expect the sw.js to be there everytime after running "npm run devWithSW" so that a service worker is properly loaded in the browser.

**Steps to reproduce:**
Using Visual Code for the Ionic PWA Toolkit, run build. Note the sw.js file in the build folder (www). Now, run devWithSW and note how the sw.js is deleted and that there is no service worker loaded in the browser. This does not occur eveytime, but enough times where you should be able to replicate it after a few tries.

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by kael** [comment]
Mentioned also in https://github.com/ionic-team/stencil/issues/789

**Comment by jgw96** [comment]
Closing this on favor of the linked stencil issue. Thanks everyone!
