### ISSUE TITLE
Run Time Error on Build

### ISSUE THREAD

**Issue by cnhnet** [ionic-team/ionic-pwa-toolkit#58]
**Resources:**
Before submitting an issue, please consult our [docs](https://stenciljs.com/).

**Stencil version:** (run `npm list @stencil/core` from a terminal/cmd prompt and paste output below):

```
`-- @stencil/core@0.7.26
```

**I'm submitting a ...**  (check one with "x")
[ X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
Receive the following runtime error on build:

[ ERROR ]  Runtime error detected while rendering: ion-app
           e.matchMedia is not a function TypeError: e.matchMedia is not a function
           at i (evalmachine.<anonymous>:2:2586) at e.render
           (evalmachine.<anonymous>:2:3045) at render
           (c:\Users\DT911\Documents\IONIC
           PROJECTS\my-pwa_alpha3\node_modules\@stencil\core\dist\compiler\index.js:10892:63)
           at renderUpdate (c:\Users\DT911\Documents\IONIC
           PROJECTS\my-pwa_alpha3\node_modules\@stencil\core\dist\compiler\index.js:11096:5)
           at update (c:\Users\DT911\Documents\IONIC
           PROJECTS\my-pwa_alpha3\node_modules\@stencil\core\dist\compiler\index.js:11089:13)
           at plt.queue.tick (c:\Users\DT911\Documents\IONIC
           PROJECTS\my-pwa_alpha3\node_modules\@stencil\core\dist\compiler\index.js:11015:34)
           at flush (c:\Users\DT911\Documents\IONIC
           PROJECTS\my-pwa_alpha3\node_modules\@stencil\core\dist\compiler\index.js:12241:33)
           at _combinedTickCallback (internal/process/next_tick.js:131:7) at
           process._tickCallback (internal/process/next_tick.js:180:9)

**Expected behavior:**
A successful build without any runtime errors.

**Steps to reproduce:**
Using a clean ionic/core 4.0.0-alpha.3 PWA Toolkit clone, run build.

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by manucorporat** [comment]
This will be fixed in the next version of ionic/core, as a workaround: remove the `--prerender` flag in the "build" script
