### ISSUE TITLE
Remaining reference to ToastController breaks build with latest ionic/core

### ISSUE THREAD

**Issue by codyburleson** [ionic-team/ionic-pwa-toolkit#62]
**Stencil version:** (run `npm list @stencil/core` from a terminal/cmd prompt and paste output below):

```
@stencil/core@0.8.0 
```

**I'm submitting a ...**  (check one with "x")
[X ] bug report

**Current behavior:**

After fresh setup, if you switch the version of ionic core in package.json to the latest like so:

```
 "dependencies": {
    "@ionic/core": "4.0.0-alpha.4",
    "@stencil/core": "0.8.0"
  },
```
You get a bad build with errors reporting no `ToastController` exported. There is a remaining reference to ToastController that needs to be changed to:

`@Prop({ connect: 'ion-toast-controller' }) toastCtrl: HTMLIonToastControllerElement;`

...which fixes the build.

It's either in my-app or app-profile; can't remember.

**Comment by jgw96** [comment]
Hello all, this has since been fixed. Thanks for using the Ionic PWA Toolkit!

**Comment by numerized** [comment]
hello here, this issue is back with a fresh git clone of this ionic-pwa-toolkit

HTMLIonToastControllerElement

```[ ERROR ]  TypeScript: ./src/components/app-root/app-root.tsx:14:14
           Cannot find name 'HTMLIonToastControllerElement'.

     L13:    @Prop({ connect: "ion-toast-controller" })
     L14:    toastCtrl: HTMLIonToastControllerElement;

[06:40.3]  build failed, watching for changes... in 1.34 s```
