### ISSUE TITLE
Make possible to change Application's Variables Color in a single file

### ISSUE THREAD

**Issue by luispalacios270** [ionic-team/ionic-pwa-toolkit#64]
**Resources:**
Already check the documentation and the feature is not ready yet.

**Stencil version:** @stencil/core@0.7.24

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
Right now is not possible to change the THEME colors variable of the application as you can in IONIC because the variable are taken from a file in the Node_Module folder.

**Expected behavior:**
Be able to change the applications colors as easily as you can in IONIC just changing a file as you can in IONIC in the theme.scss file.

**Steps to reproduce:**
Create a new PWA Toolkit app

**Other information:**
Even thought you can actually change the colors through component scss files and the global scss file it would be way more easier to mantain if you can change the application color in a file as you can do in IONIC, Since this affect pretty much every component built-in the PWA Toolkit.

**Comment by jgw96** [comment]
Hello! I recently updated this to include https://github.com/ionic-team/ionic-pwa-toolkit/blob/master/src/global/app.css which allows you to change the theme from one file. Thanks!
