### ISSUE TITLE
Failure with 'npm start'

### ISSUE THREAD

**Issue by ShawnTalbert** [ionic-team/ionic-pwa-toolkit#69]
**Resources:**

**Stencil version:** (run `npm list @stencil/core` from a terminal/cmd prompt and paste output below):

```
@stencil/starter@0.0.1 /dev/shm/baz
└── UNMET DEPENDENCY @stencil/core@0.9.6 
```

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

>  npm init stencil
> npx: installed 1 in 1.146s
> 👋  Welcome to Stencil Create App!
> 
>    What kind of project do you want to create? 
> 
> ✔ Pick a starter › 💎  ionic-pwa   (Everything you need to build fast, production ready PWAs)
> ✔ Project name … bar
> 
> We are about to clone "ionic-team/ionic-pwa-toolkit" into "./bar"
> ✔ Confirm? … yes
> 
>  💎  Cloning ionic-team/ionic-pwa-toolkit...
>  🏃‍  Changing directories...
>  ✂️  Preparing repo...
>  📦  Installing packages...
> 
>  🎉  All done!
> 
> 	cd ./bar
> 	npm start
> 
> Check out the docs: https://stenciljs.com/pwa/
> 
> shawn@shawn /run/shm $ cd ./bar
> shawn@shawn /run/shm/bar $ npm start
> 
> > @stencil/starter@0.0.1 start /dev/shm/bar
> > npm run dev
> 
> 
> > @stencil/starter@0.0.1 dev /dev/shm/bar
> > sd concurrent "stencil build --dev --watch" "stencil-dev-server" 
> 
> sh: 1: sd: not found
> npm ERR! file sh
> npm ERR! code ELIFECYCLE
> npm ERR! errno ENOENT
> npm ERR! syscall spawn
> npm ERR! @stencil/starter@0.0.1 dev: `sd concurrent "stencil build --dev --watch" "stencil-dev-server" `
> npm ERR! spawn ENOENT
> npm ERR! 
> npm ERR! Failed at the @stencil/starter@0.0.1 dev script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/shawn/.npm/_logs/2018-06-15T18_16_40_030Z-debug.log
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! @stencil/starter@0.0.1 start: `npm run dev`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the @stencil/starter@0.0.1 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/shawn/.npm/_logs/2018-06-15T18_16_40_040Z-debug.log
> 

**Other information:**
there is no 'sd' command built in nor listed as a npm dependency. I'm running Linux Mint 18.3

Note that I started this with `npm init stencil`, selecting the PWA option,  which completed without error.

**Comment by adamdbradley** [comment]
Thanks for creating the issue, this should be resolved now, thanks
