### ISSUE TITLE
ion-icon not displaying

### ISSUE THREAD

**Issue by marcjulian** [ionic-team/ionic-pwa-toolkit#7]
**Resources:**
Before submitting an issue, please consult our [docs](https://stenciljs.com/).

**Stencil version:** (run `npm list @stencil/core` from a terminal/cmd prompt and paste output below):

```
@stencil/core@0.1.3
```

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
I added an ion-icon to the toolbar and the icon is not shown.

**Expected behavior:**
Shows the ionic icon in the toolbar.

**Related code:**

```
<ion-header md-height='56px'>
     <ion-toolbar color='primary'>
	 <ion-buttons>
              <ion-icon id='ionic-icon' name='ionic'></ion-icon>
	 </ion-buttons>
         <ion-title>Ionic PWA Toolkit</ion-title>
        </ion-toolbar>
</ion-header>
```

**Comment by jgw96** [comment]
Hello! This is solved in the latest release of ionic/core (:

**Comment by thielCole** [comment]
@jgw96 I don't believe this to be fixed actually in the development environment. It seems like it might solve itself in the production environment, but I haven't tested it yet.

If I run this HTML

```html
          <div class="voting">
              <button> <ion-icon id="ionic-icon" name="ionic"></ion-icon> </button>
              <button> <ion-icon name="ionic"></ion-icon> </button>
          </div>
```

I get a 404 error in the console for the file

```
http://localhost:3333/build/app/svg/md-ionic.js
```

Running 
```
@stencil/core@0.6.1
```

**Comment by gilhardl** [comment]
@thielCole I get the same error, I just run `run-script build` then re-run usual `npm start` and ion-icon works again
