### ISSUE TITLE
Set the GitHub URL of this repo

### ISSUE THREAD

**Issue by dandv** [ionic-team/ionic-pwa-toolkit#75]
There could be a URL at https://github.com/ionic-team/ionic-pwa-toolkit after the repo description, presumably https://stenciljs.com/pwa/

**Comment by jgw96** [comment]
Good point and we actually have the perfect page now! https://ionicframework.com/pwa/toolkit. Ill add this really quick. Thanks for using the Ionic PWA Toolkit!
