### ISSUE TITLE
Don't disable text selection

### ISSUE THREAD

**Issue by dandv** [ionic-team/ionic-pwa-toolkit#77]
I wanted to select text from the welcome message, but `user-select` was set to `none`. That's annoying :)

**Comment by jgw96** [comment]
Hey! This is definitely something us to consider, leaving this issue open for now to discuss. Thanks!

**Comment by manucorporat** [comment]
Fixed by https://github.com/ionic-team/ionic/commit/8a1ad1da2c2d62ea397bb847f9dff0502148ffb3

Thanks for opening the issue!
