### ISSUE TITLE
Blank name on the Profile page

### ISSUE THREAD

**Issue by dandv** [ionic-team/ionic-pwa-toolkit#78]
I've just cloned this repo, ran `npm install` then `npm start`, and at http://localhost:3333/profile/ionic I see 
![image](https://user-images.githubusercontent.com/33569/42742902-e98765c0-8873-11e8-9663-8ab940e6aecb.png)

The page could explain how to pass the name parameter. I tried `/profile/ionic?name=joe` but that didn't help.

**Comment by kael** [comment]
The path to pass is of type `<ion-route url="/profile/:name" component="app-profile" />`. See in [my-app.tsx](https://github.com/ionic-team/ionic-pwa-toolkit/blob/3d1d0f78121a62a5cbf92988d6c039fb4730e52f/src/components/my-app/my-app.tsx#L38).

**Comment by davec21** [comment]
Getting this too, looks like the parameter isn't being properly passed through? I tried changing the name of the property to person and it is still blank. Console.logging the passed in param is dumping an object not the expected string.

**Comment by kael** [comment]
Lazy to test, what gives:  http://localhost:3333/profile/foo & http://localhost:3333/profile/bar ?

**Comment by davec21** [comment]
Not sure what you mean, but when I do it it just treats it like no parameter is passed.

**Comment by sudsy** [comment]
Yep, seeing this too. Tried to find some docs or a test for path matching for ion-router. Had a look [here:](https://github.com/ionic-team/ionic/tree/master/core/src/components/router) but didn't find anything that helped.

**Comment by jwuliger** [comment]
Same problem here :/

**Comment by arby50** [comment]
In AppProfile, the following line(s) is the problem:
  @Prop({ connect: 'ion-toast-controller' })
  @Prop() name: string;    

switch the order:
  @Prop() name: string;  
  @Prop({ connect: 'ion-toast-controller' }) 

and it works.  I changed the Prop name to "naaaaame" and did a global search using Chrome DevTools to see that it was a property of the ion-toast-controller until I switched the order.

**Comment by jwuliger** [comment]
Thanks @arby50 I cant believe I missed that lol. Good deal!

**Comment by jgw96** [comment]
Hello all! I just pushed a commit to the Toolkit to fix this issue. Thanks!
