### ISSUE TITLE
processAppGraph, unable to find tag: ion-icon at addDeps

### ISSUE THREAD

**Issue by arby50** [ionic-team/ionic-pwa-toolkit#79]
@stencil/core@0.10.7

I cloned the repo and created 'my-app', npm install, npm start and the app worked.  I could stop the app, restart, edit, etc.  Wait 24 hours and and "npm start" results in the above error and the app wont run.

I created 'my-app2' via the same technique, assuming I had somehow corrupted the proj, exact same result after 24 hours.

I created 'my-app3' via the same technique but kept a copy.  Same result, the app was fine two days ago, all I did this morning was Terminate batch job and run 'npm start' to reproduce this error.  The key difference that I found was in the auto-generated file 'component.d.ts'.  The original file had the following line that is now missing from the current file:
_import 'ionicons';_

Adding that line to the file won't work since the file is auto-generated.  I tried adding the following line to package.json:
"ionicons": "^4.2.4"
same error.

I tried 'npm install ionicons', same error.  same with 'npm install ionicons --save', just in case, but same error.

/node_modules contains the folder 'ionicons' in each of the three apps.

stack trace:
[ ERROR ]  processAppGraph, unable to find tag: ion-icon at addDeps
           (D:\dev\my-app3\node_modules\@stencil\core\dist\compiler\index.js:16689:19) at
           Array.forEach (native) at addDeps
           (D:\dev\my-app3\node_modules\@stencil\core\dist\compiler\index.js:16697:22) at
           Array.forEach (native) at addDeps
           (D:\dev\my-app3\node_modules\@stencil\core\dist\compiler\index.js:16697:22) at
           Array.forEach (native) at getGraph
           (D:\dev\my-app3\node_modules\@stencil\core\dist\compiler\index.js:16699:15) at
           processAppGraph
           (D:\dev\my-app3\node_modules\@stencil\core\dist\compiler\index.js:16567:19) at
           processAppComponentEntryTags
           (D:\dev\my-app3\node_modules\@stencil\core\dist\compiler\index.js:16728:12) at
           generateComponentEntries
           (D:\dev\my-app3\node_modules\@stencil\core\dist\compiler\index.js:16714:24)

resulting app is stuck spinning on:
Initializing First Build...

**Comment by mrlund** [comment]
I hit this issue after trying to update @ionic/core to alpha.11 oddly it doesn't revert when going back to alpha.8.

**Comment by arby50** [comment]
if you need a temporary workaround, goto:
\\node_modules\@stencil\core\dist\compiler\index.js
line 16689, change to:
            //throw new Error(`processAppGraph, unable to find tag: ${tag}`);
            return null;

not sure of the impact of this temporary workaround, but I am assuming ionicons display would be affected.

**Comment by arjunyel** [comment]
Still issue with `    "@ionic/core": "4.0.0-beta.0",
    "@stencil/core": "0.10.10"`

**Comment by manucorporat** [comment]
Seems like an issue related with cache in stencil, removing manually the `.stencil` folder seems to fix it:

Workaround:
```
rm -rf .stencil
```

cc @adamdbradley: i have been able to reproduce this issue already many times

**Comment by adamdbradley** [comment]
I think I've tracked down the issue, so we'll be able to get this fixed in stencil. Thanks for the report!
