### ISSUE TITLE
npm start fails on Windows

### ISSUE THREAD

**Issue by joshas** [ionic-team/ionic-pwa-toolkit#8]
**Stencil version:** (run `npm list @stencil/core` from a terminal/cmd prompt and paste output below):

```
@stencil/starter@0.0.1 d:\test\my-pwa
`-- @stencil/core@0.1.6
```

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
Running `npm start` on Windows 7 64bit with node v8.9.4 and npm 5.6.0 results in error. Browser is opened with "Initializing First Build..." title, but app build errors out.
```
[59:47.8]  @stencil/core v0.1.6
[59:47.8]  build, app, dev mode, started ...
[59:47.8]  compile started ...
[59:47.8]  compile finished in less than 1 ms
[59:48.4]  generate bundles started ...
[59:48.4]  generate bundles finished in less than 1 ms

[ ERROR ]  Component tag "app-home" is defined in a bundle but no matching compo
nent was found within this app or
           collections.

[ ERROR ]  Component tag "my-app" is defined in a bundle but no matching compone
nt was found within this app or
           collections.

[ ERROR ]  Component tag "app-profile" is defined in a bundle but no matching co
mponent was found within this app or
           collections.

[ ERROR ]  Component tag "lazy-img" is defined in a bundle but no matching compo
nent was found within this app or
           collections.

[59:48.8]  build failed, watching for changes... in 999 ms
``` 

**Expected behavior:**
App is built without errors.

**Steps to reproduce:**
Use "Getting Started" instructions from README.md

**Comment by jcyh0120** [comment]
+1,  I run npm start and it just show loading for a long time.

**Comment by newtonmunene99** [comment]
I also run npm start and it shows "building for first time" for endless hours. When I cancel the process and run again my system becomes unresponsive

**Comment by jgw96** [comment]
Looking into this now. Thanks for opening an issue with us!

**Comment by jgw96** [comment]
Hello all! Are you still able to reproduce this with the updated dependencies in this starter?

**Comment by joshas** [comment]
dev and build scripts work correctly on Windows 7 now. Thanks.

**Comment by szerner** [comment]
I'm having that same issue on my Windows 10 machine:

```
D:\test\ionic\my-pwa>npm start

> @stencil/starter@0.0.1 start D:\test\ionic\my-pwa
> npm run dev


> @stencil/starter@0.0.1 dev D:\test\ionic\my-pwa
> sd concurrent "stencil build --dev --watch" "stencil-dev-server"

[07:14.0]  @stencil/core v0.2.1
[07:14.0]  build, app, dev mode, started ...
[07:14.0]  compile started ...
[07:14.1]  compile finished in 16 ms

[ ERROR ]  Component tag "app-home" is defined in a bundle but no matching component was found within this app or
           collections.

[ ERROR ]  Component tag "my-app" is defined in a bundle but no matching component was found within this app or
           collections.

[ ERROR ]  Component tag "app-profile" is defined in a bundle but no matching component was found within this app or
           collections.

[ ERROR ]  Component tag "lazy-img" is defined in a bundle but no matching component was found within this app or
           collections.

[ ERROR ]  rollup died at D:\test\ionic\my-pwa\node_modules\@stencil\core\dist\compiler\index.js:3481:19 at
           Generator.next (<anonymous>) at fulfilled
           (D:\test\ionic\my-pwa\node_modules\@stencil\core\dist\compiler\index.js:3447:58) at <anonymous>

[07:15.7]  build failed, watching for changes... in 1.61 s
```

node v8.9.4
npm v5.6.0

**Comment by szerner** [comment]
Seems to be related to [this stencil issue](https://github.com/ionic-team/stencil/issues/410). I also happened to have a 'test' folder within my project path (`'D:\test\ionic\my-pwa`').
When I create the project on the root level of my drive, everything works as expected.
