### ISSUE TITLE
Demo: AppHome loaded twice

### ISSUE THREAD

**Issue by kael** [ionic-team/ionic-pwa-toolkit#85]
**Stencil version**:

```
@stencil/core v0.12.4
```

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**

Loading the demo, the _AppHome_ component is loaded twice.

**Expected behavior:**

**Steps to reproduce:**

```bash
$ npx create-stencil ionic-pwa
...
cd myapp && npm run start.sw
```

![stencil-dupe-load](https://user-images.githubusercontent.com/2463/45382928-1ac75780-b60a-11e8-9000-39cceae2dff1.png)

**Comment by manucorporat** [comment]
Should be fixed now
