### ISSUE TITLE
Stencil 0.7.0 with ionic/core 4.0.0 don't work

### ISSUE THREAD

**Issue by felipeegasneris** [ionic-team/ionic-pwa-toolkit#98]
I clone the repo, ran npm run dev and i have the `Typescript Error Interface 'IntrinsicElements'` with @ionic/core, on mac osx with node 10.

the stencil error page:

![captura de pantalla 2019-01-31 a la s 12 46 43](https://user-images.githubusercontent.com/15789058/52065933-52518480-2556-11e9-9b3a-41eaf9595fd9.png)

**Comment by arjunyel** [comment]
Stencil and ionic have been updated, should be fixed now. Thank you for the report!
